export type Lang = 'en' | 'fa';

export const siteData = {
  en: {
    nav: {
      skills: 'Skills',
      experience: 'Experience',
      education: 'Education',
      contact: 'Contact',
      langLabel: 'فارسی',
    },
    hero: {
      badge: 'Open to new opportunities',
      name: 'Sana Afshani',
      nameWords: ['Sana', 'Afshani'],
      titles: ['Front-End Developer', 'React.js Specialist', 'Next.js Engineer', 'TypeScript Expert'],
      bioBrief: 'Front-End Developer · React.js & Next.js Specialist',
      bio: 'Experienced Front-End Developer with 5+ years specializing in React.js and Next.js for building scalable web applications. Proven expertise in implementing user-friendly designs, optimizing workflows, and delivering high-performance features that exceed project requirements. Committed to clean coding practices, collaborative development, and continuous learning in emerging technologies.',
      contactCta: 'Get in Touch',
      cvCta: 'Download CV',
    },
    contact: {
      email: 'afshani.sh@gmail.com',
      phone: '09033109774',
      location: 'Tehran, Tehranpars',
      github: 'sanaafshani',
      githubUrl: 'https://github.com/sanaafshani',
      linkedin: 'sana-afshani',
      linkedinUrl: 'https://linkedin.com/in/sana-afshani',
    },
    stats: [
      { value: '5+', label: 'Years of Experience' },
      { value: '18%', label: 'PI Improvement · Snapp Doctor' },
      { value: '30%', label: 'Platform Speed Boost' },
      { value: '95%+', label: 'Test Coverage · Khodro45' },
    ],
    skills: [
      { category: 'Languages & Frameworks', items: ['React.js', 'Next.js', 'TypeScript', 'JavaScript'] },
      { category: 'Styling & UI Frameworks', items: ['Material-UI', 'Tailwind CSS', 'styled-components', 'SCSS', 'Sass', 'CSS3', 'HTML5'] },
      { category: 'State Management & Architecture', items: ['Redux', 'Context API', 'Zustand', 'Recoil'] },
      { category: 'API Integration', items: ['GraphQL', 'REST APIs', 'Axios'] },
      { category: 'Performance Optimization', items: ['Incremental Static Regeneration (ISR)', 'Lazy Loading', 'Caching', 'Code Splitting'] },
      { category: 'Testing & Quality Assurance', items: ['Cypress', 'Jest.js', 'React Testing Library'] },
      { category: 'Development Tools & Environment', items: ['Git', 'GitHub', 'ESLint', 'Prettier'] },
      { category: 'Deployment & Hosting', items: ['Vercel', 'CI/CD Pipelines'] },
      { category: 'Design & Collaboration', items: ['Figma', 'Adobe XD'] },
      { category: 'Form Handling', items: ['React Hook Form', 'Formik'] },
    ],
    experience: [
      {
        company: 'Snapp Doctor Co.',
        website: 'https://snappdoctor.ir',
        role: 'Front-End Developer',
        period: 'Dec 2023 – Jun 2025',
        colorKey: 'red' as const,
        highlights: [
          'Played a key role in the Pharmacy-Multi-assign project, designing a smart-assignment feature that automated task distribution and directly led to an 18% improvement in the Product Performance Index (PI).',
          'Drove a 30% improvement in platform speed by refactoring legacy code, introducing modular components, and optimizing the main landing page with code splitting and lazy loading.',
          'Engineered an advanced appointment reservation system with an interactive calendar and slot management, reducing customer support tickets related to scheduling by 25%.',
          'Developed comprehensive internal tools for expert schedule and availability management, creating intuitive and modular UI flows in collaboration with design and backend teams.',
          'Modernized the main landing page under a tight deadline, delivering a new, responsive design that enhanced the user experience and aligned with new product strategy.',
        ],
      },
      {
        company: 'Khodro45 Co.',
        website: 'https://khodro45.com',
        role: 'Front-End Developer',
        period: 'Nov 2022 – Nov 2023',
        colorKey: 'orange' as const,
        highlights: [
          'Developed features for the car sales journey, including UI for dynamic workflows and sales processes.',
          'Built a robust sales invoice management system with filtering, editing, and printing capabilities.',
          'Improved performance scores by optimizing for SEO and load speed, increasing the Google Lighthouse score from 75 to 92.',
          'Used ISR to deliver faster page loads and content delivery.',
          'Achieved 95%+ test coverage using Jest, ensuring product stability.',
          'Worked in an Agile environment, actively participating in planning, reviews, and retrospectives.',
        ],
      },
      {
        company: 'Digify Co. (Powered by DigiKala)',
        website: 'https://digify.ir',
        role: 'Front-End Developer',
        period: 'May 2022 – Nov 2022',
        colorKey: 'pink' as const,
        highlights: [
          'Improved scalability by implementing custom GraphQL queries and reusable UI hooks.',
          'Integrated Hotjar to monitor user behavior and track performance across multiple micro frontends.',
          'Developed 25+ automated tests to boost reliability and reduce post-release bugs.',
          'Ensured code reusability and modularity, accelerating the development of shared components.',
        ],
      },
      {
        company: 'Alaedin Group (AMA Co.)',
        website: 'https://alaedin.com',
        role: 'Front-End Developer',
        period: 'Dec 2020 – Apr 2022',
        colorKey: 'green' as const,
        highlights: [
          'Delivered mobile-first, responsive designs with reusable UI patterns and clean architecture.',
          'Optimized performance for SEO and load speed.',
          'Contributed to internal component library standards for team-wide reuse and scalability.',
        ],
      },
    ],
    education: [
      {
        school: 'Azad University, South Tehran Branch',
        degree: "Master's in Software Engineering",
        year: 'In Progress',
      },
      {
        school: 'Azad University, South Tehran Branch',
        degree: "Bachelor's in Electrical and Electronics Engineering",
        year: '2022',
      },
    ],
    sectionLabels: {
      skills: 'What I work with',
      experience: "Where I've worked",
      education: 'Academic background',
      contact: "Let's connect",
    },
    skillsTitle: 'Technical Skills',
    experienceTitle: 'Professional Experience',
    educationTitle: 'Education',
    contactTitle: "Let's Work Together",
    contactSubtitle: "Currently open to new opportunities. If you'd like to discuss a project, explore a collaboration, or simply connect professionally — feel free to reach out.",
    footerText: '© 2025 Sana Afshani · Built with Next.js',
    availableBadge: 'Available for opportunities',
    downloadLabel: 'Download PDF',
    savePdfLabel: 'Save as PDF',
    scanLabel: 'Scan to download resume PDF',
    scanSublabel: 'Downloads resume PDF',
    directDownload: 'Direct download',
  },

  fa: {
    nav: {
      skills: 'مهارت‌ها',
      experience: 'تجربه',
      education: 'تحصیلات',
      contact: 'تماس',
      langLabel: 'English',
    },
    hero: {
      badge: 'آماده همکاری',
      name: 'ثنا افشانی',
      nameWords: ['ثنا', 'افشانی'],
      titles: ['توسعه‌دهنده فرانت‌اند', 'متخصص React.js', 'مهندس Next.js', 'متخصص TypeScript'],
      bioBrief: 'توسعه‌دهنده فرانت‌اند · متخصص React.js و Next.js',
      bio: 'توسعه‌دهنده فرانت‌اند با بیش از ۵ سال تخصص در React.js و Next.js برای ساخت اپلیکیشن‌های وب مقیاس‌پذیر. تخصص اثبات‌شده در پیاده‌سازی طراحی‌های کاربرپسند، بهینه‌سازی فرآیندها و ارائه قابلیت‌های با عملکرد بالا. متعهد به اصول کدنویسی تمیز، توسعه مشارکتی و یادگیری مستمر فناوری‌های نوین.',
      contactCta: 'تماس بگیرید',
      cvCta: 'دانلود رزومه',
    },
    contact: {
      email: 'afshani.sh@gmail.com',
      phone: '09033109774',
      location: 'تهران، تهرانپارس',
      github: 'sanaafshani',
      githubUrl: 'https://github.com/sanaafshani',
      linkedin: 'sana-afshani',
      linkedinUrl: 'https://linkedin.com/in/sana-afshani',
    },
    stats: [
      { value: '5+', label: 'سال تجربه' },
      { value: '18%', label: 'بهبود شاخص PI · اسنپ دکتر' },
      { value: '30%', label: 'افزایش سرعت پلتفرم' },
      { value: '95%+', label: 'پوشش تست · خودرو۴۵' },
    ],
    skills: [
      { category: 'زبان‌ها و فریمورک‌ها', items: ['React.js', 'Next.js', 'TypeScript', 'JavaScript'] },
      { category: 'استایل و UI', items: ['Material-UI', 'Tailwind CSS', 'styled-components', 'SCSS', 'Sass', 'CSS3', 'HTML5'] },
      { category: 'مدیریت حالت و معماری', items: ['Redux', 'Context API', 'Zustand', 'Recoil'] },
      { category: 'یکپارچه‌سازی API', items: ['GraphQL', 'REST APIs', 'Axios'] },
      { category: 'بهینه‌سازی عملکرد', items: ['ISR', 'Lazy Loading', 'Caching', 'Code Splitting'] },
      { category: 'تست و کیفیت', items: ['Cypress', 'Jest.js', 'React Testing Library'] },
      { category: 'ابزارهای توسعه', items: ['Git', 'GitHub', 'ESLint', 'Prettier'] },
      { category: 'استقرار و هاستینگ', items: ['Vercel', 'CI/CD Pipelines'] },
      { category: 'طراحی و همکاری', items: ['Figma', 'Adobe XD'] },
      { category: 'مدیریت فرم', items: ['React Hook Form', 'Formik'] },
    ],
    experience: [
      {
        company: 'Snapp Doctor Co.',
        website: 'https://snappdoctor.ir',
        role: 'توسعه‌دهنده فرانت‌اند',
        period: 'دی ۱۴۰۲ – شهریور ۱۴۰۴',
        colorKey: 'red' as const,
        highlights: [
          'نقش کلیدی در پروژه Pharmacy-Multi-assign با طراحی ویژگی تخصیص هوشمند که توزیع وظایف را خودکار کرد و مستقیماً به بهبود ۱۸٪ در شاخص عملکرد محصول (PI) منجر شد.',
          'بهبود ۳۰٪ در سرعت پلتفرم از طریق ریفکتور کد قدیمی، معرفی کامپوننت‌های ماژولار و بهینه‌سازی صفحه اصلی با Code Splitting و Lazy Loading.',
          'طراحی سیستم پیشرفته رزرو نوبت با تقویم تعاملی و مدیریت اسلات — کاهش ۲۵٪ تیکت‌های پشتیبانی مرتبط با زمان‌بندی.',
          'توسعه ابزارهای داخلی جامع برای مدیریت برنامه و دسترسی متخصصان با رابط‌های UI ماژولار در همکاری با تیم‌های طراحی و بکند.',
          'بازطراحی صفحه اصلی تحت ددلاین سخت با طراحی ریسپانسیو که تجربه کاربری را بهبود بخشید و با استراتژی محصول جدید همسو شد.',
        ],
      },
      {
        company: 'Khodro45 Co.',
        website: 'https://khodro45.com',
        role: 'توسعه‌دهنده فرانت‌اند',
        period: 'آبان ۱۴۰۱ – آبان ۱۴۰۲',
        colorKey: 'orange' as const,
        highlights: [
          'توسعه قابلیت‌های سفر فروش خودرو شامل UI برای گردش‌کارهای داینامیک و فرآیندهای فروش.',
          'ساخت سیستم مدیریت فاکتور فروش با قابلیت‌های فیلترینگ، ویرایش و پرینت.',
          'بهبود امتیاز عملکرد از طریق بهینه‌سازی SEO و سرعت بارگذاری — امتیاز Google Lighthouse از ۷۵ به ۹۲.',
          'استفاده از ISR برای بارگذاری سریع‌تر صفحات و ارائه محتوا.',
          'پوشش تست ۹۵٪+ با Jest برای اطمینان از پایداری محصول.',
          'کار در محیط Agile با مشارکت فعال در برنامه‌ریزی، بررسی‌ها و رتروسپکتیوها.',
        ],
      },
      {
        company: 'Digify Co. (Powered by DigiKala)',
        website: 'https://digify.ir',
        role: 'توسعه‌دهنده فرانت‌اند',
        period: 'اردیبهشت ۱۴۰۱ – آبان ۱۴۰۱',
        colorKey: 'pink' as const,
        highlights: [
          'بهبود مقیاس‌پذیری با کوئری‌های سفارشی GraphQL و UI Hook‌های قابل استفاده مجدد.',
          'یکپارچه‌سازی Hotjar برای نظارت بر رفتار کاربر و ردیابی عملکرد در میکروفرانت‌اندهای مختلف.',
          'توسعه بیش از ۲۵ تست خودکار برای افزایش قابلیت اطمینان و کاهش باگ‌های پس از انتشار.',
          'تضمین قابلیت استفاده مجدد و ماژولار بودن کامپوننت‌های مشترک.',
        ],
      },
      {
        company: 'Alaedin Group (AMA Co.)',
        website: 'https://alaedin.com',
        role: 'توسعه‌دهنده فرانت‌اند',
        period: 'آذر ۱۳۹۹ – فروردین ۱۴۰۱',
        colorKey: 'green' as const,
        highlights: [
          'ارائه طراحی‌های ریسپانسیو Mobile-First با الگوهای UI قابل استفاده مجدد و معماری تمیز.',
          'بهینه‌سازی عملکرد برای SEO و سرعت بارگذاری.',
          'مشارکت در استانداردهای کتابخانه کامپوننت داخلی برای استفاده تیمی و مقیاس‌پذیری.',
        ],
      },
    ],
    education: [
      {
        school: 'دانشگاه آزاد اسلامی، واحد تهران جنوب',
        degree: 'کارشناسی ارشد مهندسی نرم‌افزار',
        year: 'در حال تحصیل',
      },
      {
        school: 'دانشگاه آزاد اسلامی، واحد تهران جنوب',
        degree: 'کارشناسی مهندسی برق و الکترونیک',
        year: '۱۴۰۱',
      },
    ],
    sectionLabels: {
      skills: 'با چه چیزی کار می‌کنم',
      experience: 'کجاها کار کردم',
      education: 'سابقه تحصیلی',
      contact: 'بیایید در ارتباط باشیم',
    },
    skillsTitle: 'مهارت‌های فنی',
    experienceTitle: 'تجربه حرفه‌ای',
    educationTitle: 'تحصیلات',
    contactTitle: 'همکاری حرفه‌ای',
    contactSubtitle: 'جهت همکاری حرفه‌ای، مشاوره فنی یا هرگونه پرسش، از طریق راه‌های ارتباطی زیر در دسترس هستم.',
    footerText: '© ۱۴۰۴ ثنا افشانی · ساخته شده با Next.js',
    availableBadge: 'آماده همکاری',
    downloadLabel: 'دانلود PDF',
    savePdfLabel: 'ذخیره PDF',
    scanLabel: 'اسکن کن، رزومه PDF دانلود میشه',
    scanSublabel: 'دانلود فایل PDF رزومه',
    directDownload: 'دانلود مستقیم',
  },
};
